# 기본 활성화 룰 중 비활성화할 룰들
disabled_rules:
- line_length
- trailing_whitespace
- orphaned_doc_comment
- nesting
- function_body_length
- function_parameter_count

# 기본 룰이 아닌 룯 설정
opt_in_rules:
- anyobject_protocol
- let_var_whitespace

# 린트를 포함할 파일 경로
included:

# 린트를 포함하지 않을 경로
excluded:
- SobokSobok/Application # AppDelegate, SceneDelegate 파일 무시
- SobokSobok/Common/NameSpace

identifier_name:
  excluded:
    - id

force_cast:
    warning              # 강제 캐스팅은 error에서 warning으로 변경
